<a href="https://colab.research.google.com/github/gulistanergun/VeriBilimineGirisOdev/blob/main/python_odev_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
#Soru 1 – Liste Metotları

"""
Bir sınıfta öğrencilerin notları şu şekilde tutuluyor:
notlar = [85, 92, 76, 92, 100, 76, 85, 92]
• Listedeki tekrar eden notları silip benzersiz bir liste oluşturun.
• En yüksek ve en düşük notu bulun.
• Notları küçükten büyüğe sıralayın.
"""

notlar = [85, 92, 76, 92, 100, 76, 85, 92]
print(f"Tüm notlar: {notlar}")

# Tekrar eden notları silme - set() kullanarak benzersiz değerler
benzersiz_liste = list(set(notlar))
print(f"Benzersiz notlar: {benzersiz_liste}")

# En yüksek ve en düşük not
en_yuksek = max(notlar)
en_dusuk = min(notlar)
print(f"En yüksek not: {en_yuksek}")
print(f"En düşük not: {en_dusuk}")

# Notları sıralama
sirali_liste = sorted(notlar)
print(f"Sıralı notlar: {sirali_liste}")
sirali_liste_benzersiz = sorted(set(notlar))
print(f"Sıralı notlar: {sirali_liste_benzersiz}")




Tüm notlar: [85, 92, 76, 92, 100, 76, 85, 92]
Benzersiz notlar: [100, 92, 85, 76]
En yüksek not: 100
En düşük not: 76
Sıralı notlar: [76, 76, 85, 85, 92, 92, 92, 100]
Sıralı notlar: [76, 85, 92, 100]


In [10]:
"""
Soru 2 – Sayılar
Bir sayının Armstrong sayısı olup olmadığını kontrol eden bir Python fonksiyonu yazın.
Armstrong sayısı: Her basamağının küplerinin toplamı kendisine eşit olan sayılar.
Örn: 153 → 1³+5³+3³ = 153
"""
def armstrong_sayi(sayi):
    str_sayi = str(sayi)               # stringe çeviriyoruz
    basamak_sayisi = len(str_sayi)     # Basamak sayısını bul
    toplam = 0

    print(f"Sayı: {sayi}")
    print(f"Basamak sayısı: {basamak_sayisi}")
    print("Basamakların kuvvetleri:")

    for basamak in str_sayi:
        rakam = int(basamak)
        kuvvet = rakam ** basamak_sayisi
        toplam += kuvvet   # her basamağın kuvvetini topla
        print(f"Basamak: {rakam}, {rakam}^{basamak_sayisi} = {kuvvet}")

    print(f"Kuvvetler toplamı: {toplam}")
    if toplam == sayi:
        print(f"{sayi} bir Armstrong sayısıdır.\n")
    else:
        print(f"{sayi} bir Armstrong sayısı değildir.\n")

sayilari = [153, 123]
for sayi in sayilari:
    armstrong_sayi(sayi)



Sayı: 153
Basamak sayısı: 3
Basamakların kuvvetleri:
Basamak: 1, 1^3 = 1
Basamak: 5, 5^3 = 125
Basamak: 3, 3^3 = 27
Kuvvetler toplamı: 153
153 bir Armstrong sayısıdır.

Sayı: 123
Basamak sayısı: 3
Basamakların kuvvetleri:
Basamak: 1, 1^3 = 1
Basamak: 2, 2^3 = 8
Basamak: 3, 3^3 = 27
Kuvvetler toplamı: 36
123 bir Armstrong sayısı değildir.



In [15]:
"""Soru 3 – Kümeler
Aşağıdaki iki küme verilmiştir:
A = {"Python", "R", "SQL", "Java"}
B = {"C++", "Python", "JavaScript", "SQL"}
• Ortak dilleri bulun.
• Sadece A’da olan dilleri listeleyin.
• İki kümenin birleşimini alfabetik olarak yazdırın
"""
A = {"Python", "R", "SQL", "Java"}
B = {"C++", "Python", "JavaScript", "SQL"}

print(f"A kümesi: {A}")
print(f"B kümesi: {B}")

ortak_diller = A & B
print(f"Ortak diller: {ortak_diller}")

A_kumesi = A - B
print(f"Sadece A'da olan diller: {A_kumesi}")

A_birlesim_B= A | B
print(f"A ve B kümelerinin birleşimi: {A_birlesim_B}")

alfabetik_sira = sorted(A|B)
print(f"Alfabetik sırada birleşim kümesi: {alfabetik_sira}")





A kümesi: {'R', 'Python', 'Java', 'SQL'}
B kümesi: {'C++', 'Python', 'SQL', 'JavaScript'}
Ortak diller: {'Python', 'SQL'}
Sadece A'da olan diller: {'R', 'Java'}
A ve B kümelerinin birleşimi: {'C++', 'Python', 'SQL', 'R', 'Java', 'JavaScript'}
Alfabetik sırada birleşim kümesi: ['C++', 'Java', 'JavaScript', 'Python', 'R', 'SQL']


In [17]:
"""
Soru 4 – Modüller
• random modülünü kullanarak 1–100 arasında 10 rastgele sayı üretin.
• Bu sayıların ortalamasını ve standart sapmasını statistics modülü ile hesaplayın.
"""
import random
import statistics

# rastgele= [random.randint(1,100) for _ in range(10)]
rastgele = []             # Boş liste
for _ in range(10):       # 10 kez dön
    sayi = random.randint(1, 100)  # 1-100 arasında rastgele sayı
    rastgele.append(sayi)
print(f"Rastgele Sayilar: {rastgele}")

ortalama = statistics.mean(rastgele)
standart_sapma = statistics.stdev(rastgele)

print(f"Ortalama: {ortalama:.2f}")
print(f"Standart sapma: {standart_sapma:.2f}")



Rastgele Sayilar: [33, 42, 24, 95, 85, 95, 53, 72, 29, 75]
Ortalama: 60.30
Standart sapma: 27.49


In [24]:
"""Soru 5 Fonksiyonlar
kelime_sayacı(metin) adında bir fonksiyon yazın.
Fonksiyon verilen metindeki:
• toplam kelime sayısını
• en uzun kelimeyi
• en sık geçen kelimeyi döndürsün
"""

def kelime_sayaci(metin):

  #toplam kelime sayisi
  kelimeler = metin.split()
  toplam_kelime= len(kelimeler)

  #en uzun kelime
  en_uzun_kelime = max(kelimeler, key=len) if kelimeler else ""


  # En sık geçen kelime
  kelime_sayilari = {}
  for kelime in kelimeler:
      kelime_sayilari[kelime] = kelime_sayilari.get(kelime, 0) + 1

  en_sik_kelime = max(kelime_sayilari, key=kelime_sayilari.get) if kelime_sayilari else ""

  return toplam_kelime, en_uzun_kelime, en_sik_kelime


ornek_metin = """Python’da rastgele sayı üretmek, listelerden rastgele seçim yapmak
  veya elemanları karıştırmak için kullanılır. Oyunlarda, simülasyonlarda
  ve test verisi üretiminde sıkça tercih edilir."""
toplam, en_uzun, en_sik = kelime_sayaci(ornek_metin)
print(f"Örnek metin: {ornek_metin}")
print(f"Toplam kelime: {toplam}")
print(f"En uzun kelime: {en_uzun}")
print(f"En sık kelime: {en_sik}")

Örnek metin: Python’da rastgele sayı üretmek, listelerden rastgele seçim yapmak 
  veya elemanları karıştırmak için kullanılır. Oyunlarda, simülasyonlarda 
  ve test verisi üretiminde sıkça tercih edilir.
Toplam kelime: 22
En uzun kelime: simülasyonlarda
En sık kelime: rastgele


In [26]:
"""
Soru 6 Gömülü Fonksiyonlar
Aşağıdaki liste için map, filter, sorted gibi gömülü fonksiyonları kullanarak:
sayilar = [5, 12, 7, 18, 24, 3, 16]
• Sadece çift sayıları filtreleyin.
• Bu sayıların karelerini bulun.
• Karelerini azalan sırada sıralayın.
"""
sayilar = [5, 12, 7, 18, 24, 3, 16]
print(f"Orijinal sayılar: {sayilar}")

# Sadece çift sayıları
cift_sayilar = list(filter(lambda x: x % 2 == 0, sayilar))
print(f"Çift sayılar: {cift_sayilar}")

# Çift sayıların kareleri
kareler = list(map(lambda x: x**2, cift_sayilar))
print(f"Çift sayıların kareleri: {kareler}")

# Kareleri azalan sırada sırala
azalan_kareler = sorted(kareler, reverse=True)
print(f"Azalan sırada kareler: {azalan_kareler}")

# Tek seferde yapılması:
tek_seferde = sorted(map(lambda x: x**2, filter(lambda x: x % 2 == 0, sayilar)), reverse=True)
print(f"Tek seferde işlemleri yapıp srala: {tek_seferde}")





Orijinal sayılar: [5, 12, 7, 18, 24, 3, 16]
Çift sayılar: [12, 18, 24, 16]
Çift sayıların kareleri: [144, 324, 576, 256]
Azalan sırada kareler: [576, 324, 256, 144]
Tek seferde işlemleri yapıp srala: [576, 324, 256, 144]


In [29]:
"""
Soru 7 – Lambda İfadeleri
Aşağıdaki listeyi, her kelimenin uzunluğuna göre küçükten büyüğe sıralayın.
kelimeler = ["veri", "bilim", "analiz", "yapayzeka", "python"]
Bunu sorted + lambda ile yapın
"""
kelimeler = ["veri", "bilim", "analiz", "yapayzeka", "python"]
print(f"Kelime Dizisi: {kelimeler}")

#sıralama
uzunluk = sorted(kelimeler, key = lambda x:len(x))
print(f"Uzunluğa göre sırala: {uzunluk}")



Kelime Dizisi: ['veri', 'bilim', 'analiz', 'yapayzeka', 'python']
Uzunluğa göre sırala: ['veri', 'bilim', 'analiz', 'python', 'yapayzeka']


In [36]:
"""
Soru 8 – Metodlar
Bir string içinde geçen tüm rakamları bulun ve bunların toplamını döndüren bir fonksiyon
yazın.
Örn: "abc12def3" → 12 + 3 = 15
"""

def rakam_topla(metin):
    toplam = 0
    rakam_grubu = ""  # Rakamları biriktir

    for karakter in metin:
        if karakter.isdigit():
            rakam_grubu += karakter
        else:
            if rakam_grubu:  # grup varsa topla
                toplam += int(rakam_grubu)
                rakam_grubu = ""  # sıfırla

    if rakam_grubu:  # son grup kaldıysa ekle
        toplam += int(rakam_grubu)

    return toplam

ornek_metin = "abc12def3"
sonuc = rakam_topla(ornek_metin)
print(f"Örnek metin: {ornek_metin}")
print(f"Rakamların toplamı: {sonuc}")

Örnek metin: abc12def3
Rakamların toplamı: 15


In [39]:
"""
Soru 9 – (Ekstra) Numpy 1
10 elemanlı bir numpy dizisi oluşturun.
• Elemanlar 0–50 arasında rastgele sayılar olsun.
• Dizinin ortalamasını, standart sapmasını ve en büyük değerini bulun.
"""
import numpy as np


dizi = np.random.randint(0, 51, 10)

# Diziyi yazdır
print("Dizi:", dizi)

# Ortalama
ortalama = np.mean(dizi)
print("Ortalama:", ortalama)

# Standart sapma
standart_sapma = np.std(dizi)
print("Standart Sapma:", standart_sapma)

# En büyük değer
en_buyuk = np.max(dizi)
print("En Büyük Değer:", en_buyuk)

Dizi: [19 19 32 15 15 26 25 17 48  4]
Ortalama: 22.0
Standart Sapma: 11.251666543228163
En Büyük Değer: 48


In [45]:
"""
Soru 10 – (Ekstra) Numpy 2
5x5 boyutunda rastgele 0–1 arasında değerlerden oluşan bir numpy matrisi üretin.
• Her sütunun ortalamasını bulun.
• 0.5’ten büyük olan değerleri 1, küçük eşit olanları 0 yaparak binary matris oluşturun.
"""

import numpy as np
matris = np.random.rand(5, 5)
print("Orijinal Matris:")
print(matris)

# Sütun ortalamaları
sutun_ortalama = np.mean(matris, axis=0)
print("\nSütun Ortalamaları:\n", sutun_ortalama)

# 3. Binary matris oluştur (0.5’ten büyük -> 1, küçük eşit -> 0)
binary_matris = np.where(matris > 0.5, 1, 0)
print("\nBinary Matris:\n", binary_matris)


Orijinal Matris:
[[0.77972216 0.6826339  0.81161959 0.44422269 0.94473883]
 [0.04487265 0.55943152 0.43595844 0.09799962 0.10808127]
 [0.01911298 0.08936364 0.87800455 0.68064431 0.02394437]
 [0.20442862 0.84036797 0.32686551 0.72915301 0.40745294]
 [0.26983059 0.60954794 0.33299691 0.04346223 0.60368788]]

Sütun Ortalamaları:
 [0.2635934  0.55626899 0.557089   0.39909637 0.41758106]

Binary Matris:
 [[1 1 1 0 1]
 [0 1 0 0 0]
 [0 0 1 1 0]
 [0 1 0 1 0]
 [0 1 0 0 1]]
